-- =====================================================
-- Automated Trading Workflow Database Schema
-- PostgreSQL + pgvector for RAG-based trade analysis
-- =====================================================

-- Enable pgvector extension for similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- =====================================================
-- TRADE IDEAS TABLE
-- Stores all trade signals generated by Grok API
-- =====================================================
CREATE TABLE IF NOT EXISTS trade_ideas (
    id SERIAL PRIMARY KEY,

    -- Trade Details
    symbol VARCHAR(20) NOT NULL,
    timeframe VARCHAR(10) NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('LONG', 'SHORT', 'FLAT')),
    entry_price DECIMAL(18, 8) NOT NULL,
    stop_loss DECIMAL(18, 8) NOT NULL,
    take_profit DECIMAL(18, 8) NOT NULL,

    -- AI Analysis
    confidence DECIMAL(3, 2) NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
    rationale TEXT,
    notes TEXT,

    -- Outcome Tracking
    is_win BOOLEAN DEFAULT NULL, -- NULL = not yet evaluated, TRUE = win, FALSE = loss
    actual_exit_price DECIMAL(18, 8),
    pnl DECIMAL(18, 8),

    -- RAG/Embedding Support
    embedding vector(1536), -- OpenAI ada-002 or similar embedding dimension

    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    evaluated_at TIMESTAMP,

    -- Raw API Response (for debugging/audit)
    raw_response JSONB
);

-- Indexes for performance
CREATE INDEX idx_trade_ideas_symbol ON trade_ideas(symbol);
CREATE INDEX idx_trade_ideas_timeframe ON trade_ideas(timeframe);
CREATE INDEX idx_trade_ideas_created_at ON trade_ideas(created_at DESC);
CREATE INDEX idx_trade_ideas_confidence ON trade_ideas(confidence);
CREATE INDEX idx_trade_ideas_is_win ON trade_ideas(is_win);

-- Vector similarity search index (HNSW for fast approximate search)
CREATE INDEX idx_trade_ideas_embedding ON trade_ideas
    USING hnsw (embedding vector_cosine_ops);

-- =====================================================
-- ANALYSIS LOGS TABLE
-- Track all analysis runs, including low-confidence rejections
-- =====================================================
CREATE TABLE IF NOT EXISTS analysis_logs (
    id SERIAL PRIMARY KEY,

    -- Run Details
    run_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL, -- 'SUCCESS', 'REJECTED_LOW_CONFIDENCE', 'ERROR'

    -- Link to Trade Idea (if saved)
    trade_idea_id INTEGER REFERENCES trade_ideas(id),

    -- Confidence and Context
    confidence DECIMAL(3, 2),
    confidence_threshold DECIMAL(3, 2) DEFAULT 0.70,

    -- Prompt and Response
    prompt_text TEXT,
    grok_response JSONB,

    -- Error Tracking
    error_message TEXT,

    -- Performance Metrics
    api_latency_ms INTEGER,
    rag_context_count INTEGER
);

CREATE INDEX idx_analysis_logs_timestamp ON analysis_logs(run_timestamp DESC);
CREATE INDEX idx_analysis_logs_status ON analysis_logs(status);

-- =====================================================
-- MARKET CONTEXT TABLE (Optional)
-- Store external market data for prompt enhancement
-- =====================================================
CREATE TABLE IF NOT EXISTS market_context (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timeframe VARCHAR(10) NOT NULL,

    -- Market Data
    current_price DECIMAL(18, 8),
    volume DECIMAL(18, 2),
    market_summary TEXT,

    -- Metadata
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(100) -- 'API', 'MANUAL', etc.
);

CREATE INDEX idx_market_context_symbol_time ON market_context(symbol, timestamp DESC);

-- =====================================================
-- HELPER FUNCTIONS
-- =====================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for trade_ideas
CREATE TRIGGER update_trade_ideas_updated_at
    BEFORE UPDATE ON trade_ideas
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- EMAIL SUMMARIES TABLE
-- Store daily email summaries generated by AI
-- =====================================================
CREATE TABLE IF NOT EXISTS email_summaries (
    id SERIAL PRIMARY KEY,

    -- Summary Details
    summary_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_emails INTEGER NOT NULL,
    summary TEXT NOT NULL, -- JSON string of GrokEmailSummaryResponse

    -- AI Analysis
    confidence DECIMAL(3, 2) NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),

    -- RAG/Embedding Support
    embedding vector(1536), -- For finding similar email patterns

    -- Email References
    email_ids JSONB, -- Array of Gmail message IDs

    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_email_summaries_date ON email_summaries(summary_date DESC);
CREATE INDEX idx_email_summaries_confidence ON email_summaries(confidence);
CREATE INDEX idx_email_summaries_created_at ON email_summaries(created_at DESC);

-- Vector similarity search index
CREATE INDEX idx_email_summaries_embedding ON email_summaries
    USING hnsw (embedding vector_cosine_ops);

-- =====================================================
-- SAMPLE QUERIES (for reference)
-- =====================================================

-- Find similar past trades using vector similarity
-- SELECT id, symbol, direction, confidence, created_at
-- FROM trade_ideas
-- WHERE embedding IS NOT NULL
-- ORDER BY embedding <=> $1::vector
-- LIMIT 5;

-- Get win rate by symbol
-- SELECT
--     symbol,
--     COUNT(*) as total_trades,
--     SUM(CASE WHEN is_win = TRUE THEN 1 ELSE 0 END) as wins,
--     ROUND(AVG(CASE WHEN is_win = TRUE THEN 1 ELSE 0 END) * 100, 2) as win_rate
-- FROM trade_ideas
-- WHERE is_win IS NOT NULL
-- GROUP BY symbol
-- ORDER BY total_trades DESC;

-- Find similar email summaries using vector search
-- SELECT id, summary_date, total_emails, confidence
-- FROM email_summaries
-- WHERE embedding IS NOT NULL
-- ORDER BY embedding <=> $1::vector
-- LIMIT 5;

-- Email summary stats by date
-- SELECT
--     summary_date,
--     total_emails,
--     confidence,
--     created_at
-- FROM email_summaries
-- ORDER BY summary_date DESC
-- LIMIT 30;
