/**
 * Trade Idea Model
 * Represents a trading signal generated by Grok API
 */

export interface TradeIdea {
  id?: number;
  symbol: string;
  timeframe: string;
  direction: 'LONG' | 'SHORT' | 'FLAT';
  entry_price: number;
  stop_loss: number;
  take_profit: number;
  confidence: number;
  rationale: string;
  notes?: string;
  is_win?: boolean | null;
  actual_exit_price?: number | null;
  pnl?: number | null;
  embedding?: number[];
  created_at?: Date;
  updated_at?: Date;
  evaluated_at?: Date | null;
  raw_response?: any;
}

/**
 * Grok API Response Schema
 * This is the expected JSON format from Grok
 */
export interface GrokTradeResponse {
  symbol: string;
  timeframe: string;
  direction: 'LONG' | 'SHORT' | 'FLAT';
  entry_price: number;
  stop_loss: number;
  take_profit: number;
  confidence: number;
  rationale: string;
  notes?: string;
}

/**
 * Analysis Log Model
 * Tracks all analysis runs including rejections
 */
export interface AnalysisLog {
  id?: number;
  run_timestamp?: Date;
  status: 'SUCCESS' | 'REJECTED_LOW_CONFIDENCE' | 'ERROR';
  trade_idea_id?: number | null;
  confidence?: number | null;
  confidence_threshold?: number;
  prompt_text?: string;
  grok_response?: any;
  error_message?: string | null;
  api_latency_ms?: number | null;
  rag_context_count?: number | null;
}

/**
 * RAG Context Item
 * Represents historical trade data for prompt context
 */
export interface RAGContext {
  id: number;
  symbol: string;
  timeframe: string;
  direction: string;
  confidence: number;
  rationale: string;
  is_win?: boolean | null;
  created_at: Date;
  similarity?: number;
}
